### ISSUE TITLE
TypeError: istft() takes 1 positional argument but 3 were given

### ISSUE THREAD

**Issue by muxiddin19** [scheck-k/ste-gan#2]
Great work!
Can you please guide me while I solve the given issue:
(ste-gan) gpulab2@gpulab2:~/muhiddin/ste-gan$ python scripts/clean_audio.py raw_data/emg_data/nonparallel_data/* raw_data/emg_data/silent_parallel_data/* raw_data/emg_data/voiced_parallel_data/*
torchvision is not available - cannot save figures
cleaning raw_data/emg_data/nonparallel_data/4-21
Loading SpectralMaskEnhancement model speechbrain/metricgan-plus-voicebank
  0%|                                                                                                                                                  | 0/672 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/gpulab2/muhiddin/ste-gan/scripts/clean_audio.py", line 112, in <module>
    clean_directory(sys.argv[i])
  File "/home/gpulab2/muhiddin/ste-gan/scripts/clean_audio.py", line 89, in clean_directory
    clean = nr.reduce_noise(audio_clip=data, noise_clip=silence)
  File "/home/gpulab2/anaconda3/envs/ste-gan/lib/python3.10/site-packages/noisereduce/noisereduce.py", line 261, in reduce_noise
    recovered_signal = _istft(
  File "/home/gpulab2/anaconda3/envs/ste-gan/lib/python3.10/site-packages/noisereduce/noisereduce.py", line 24, in _istft
    return librosa.istft(y, hop_length, win_length)
TypeError: istft() takes 1 positional argument but 3 were given

**Comment by shanullah** [comment]
Hello there. @muxiddin19 , it seems you have issue with librosa version and it originated due to librosa version mismatch.

One way is to fix only librosa version , for me it worked on version  "librosa==0.10.0."
However, since many things are dependent and your other libraries needs to be compatible.

Eventhough, I am not the author of this repository, since i tested the code and worked fine for me.

For safe side, I am sharing you the complete set of libraries, my environment, which you can install or out of the list you can check versions of particular libraries. 

The environment name is the same as ste-gan, you can change the name inside the file if you already have ste-gan as your environment.
##########################
conda env create --file environment_ste_GAN_Success.yml
##########################

[environment_ste_GAN_Success.txt](https://github.com/scheck-k/ste-gan/files/15430389/environment_ste_GAN_Success.txt)
I have renamed file into .txt as  github was not allowing me to upload .yml file, please change the file to .yml and run the file as per conda command.
I hope it would work for you.

Thank you
